# Setup
title:        写给小曾
tagline:      ❤
baseurl:      "wfnian.top"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       王方年
  url:        https://xzeng.top 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown